export default [{
  user: [{
    id: 1,
    email: '',
    password: '',
    username: '',
    createdAt: '',
    updatedAt: '',
    role: [{
      id: 1,
      name: 'Utilisateur',
      role_string: 'ROLE_USER',
    }],
    cv: [{
      id: 1,
      name: '',
      createdAt: '',
      updatedAt: '',
      template: [{
        id: 2,
        name: 'model2',
        style_url: 'styles-model2.scss',
        createdAt: '2021-11-30',
        updatedAt: '2021-12-01',
      }],
    }],
    personal_data: [{
      id: 1,
      first_name: '',
      last_name: '',
      birth_date: null,
      city: '',
      adress: '',
      email: '',
      phone_nb: '',
      picture: 'https://all4prints.com/7116-large_default/sean-connery-como-james-bond.jpg',
      linkedin: '',
      content: '',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    }],
    skill: [
    ],
    education: [
    ],
    activity: [
    ],
    language: [
    ],
    work_experience: [
    ],
    social_network: [
    ],
  },

  {
    id: 2,
    email: 'homer-simpson@duff.io',
    password: 'DuffDonuts1987',
    username: 'ILOVEDUFF',
    createdAt: '2021-12-02',
    updatedAt: '2021-12-02',
    role: [{
      id: 1,
      name: 'Utilisateur',
      role_string: 'ROLE_USER',
    }],
    cv: [{
      id: 1,
      name: '',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
      template: [{
        id: 1,
        name: 'TOUT',
        style_url: 'styles-model1.scss',
        createdAt: '2021-12-02',
        updatedAt: '2021-12-02',
      }],
    }],
    personal_data: [{
      id: 1,
      first_name: 'Homer',
      last_name: 'Simpson',
      birth_date: 1987,
      city: 'Springfield',
      adress: '742 Evergreen Terrace, Springfield, États-Unis',
      email: 'homer-simpson@duff.io',
      phone_nb: '(212) 324-4152',
      picture: 'https://simpsonshop.fr/wp-content/uploads/2020/11/homer-simpson.jpg',
      linkedin: 'https://www.linkedin.com/in/homer-simpson-1242351b5/',
      content: "Je suis prêt a changer d'emploi, Mr Burn m'exploite Tfou !",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    }],
    skill: [{
      id: 1,
      title: 'Rapide',
      content: "Je bois des Duff's plus vite que n'importe qui et mange des donuts super rapidement aussi",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      title: 'Sportif',
      content: "J'arrive a courir très vite quand il faut attraper Bart",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      title: 'Calme',
      content: "J'arrive a ne pas frapper Bart tout les jours",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    ],
    education: [{
      id: 1,
      certificate: 'Diploma College',
      school_name: 'Springfild Hight School',
      city: 'Springfield',
      start_date: '1987-09-01',
      end_date: '1988-07-03',
      content: " Obtention de mon diplome d'étude",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      certificate: 'Diplome de Sécurité',
      school_name: 'Security School of Springfild',
      city: 'Springfield',
      start_date: '1990-05-20',
      end_date: '1994-08-30',
      content: 'Apprentissage de la sécurité en milieu chimique',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      certificate: 'Certificat de buveur de bière Professionnel',
      school_name: 'Duff School',
      city: 'Duff City',
      start_date: '2017-12-18',
      end_date: '2018-04-11',
      content: 'Diplome prouvant que je sais boire comme un pro mes bières Duffs',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    ],
    activity: [{
      id: 1,
      title: 'Donuts Fan Club',
      start_date: '1990-02-15',
      end_date: '',
      content: "J'ai mangé des Donuts toute ma vie, je sais reconnaitre des vraies Donuts de qualités grâce a mon club de Fan de Donuts.",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      title: " Duff's club",
      start_date: '2010-01-01',
      end_date: '',
      content: 'Je fais partie du club des Fan de Duff. Je reconnais une vraie bière Duff les yeux fermés.',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      title: "Moe's associés",
      start_date: '',
      end_date: '',
      content: 'Je participe activement à la réussite du Bar de mon amie Moe ',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    ],
    laguage: [{
      id: 1,
      name: 'Anglais',
      level: 'courant',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      name: 'Français',
      level: 'base',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      name: 'Alcolique',
      level: 'courant',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },

    ],
    work_experience: [{
      id: 1,
      company_name: 'Ecole élémentaire de Springfild',
      city: 'Springfield',
      role: "Mascotte (l'homme-salamandre) de la sécurité de l'école",
      start_date: '2005-05-08',
      end_date: '2005-05-08',
      content: "J'ai fais la mascotte pour l'école de Lisa et Bart, j'ai étais très investi.",
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      company_name: 'Kwik-E Mart',
      city: 'springfield',
      role: 'Vendeur de matelas',
      start_date: '2008-08-15',
      end_date: '2008-08-18',
      content: 'Je vendais des matelas dans la magasin de mon ami Apu.',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      company_name: 'Centrale de Springfield',
      city: 'Springfield',
      role: 'Inspecteur de sécurité',
      start_date: '2010-09-01',
      end_date: '',
      content: 'Je sui chargé de la surveillance des réacteur à la centrale nucléaire de Sprinfield.',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    ],
    social_network: [{
      id: 1,
      name: 'Facebook',
      link: 'https://www.facebook.com/homer.simpsom.3979',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 2,
      name: 'Twitter',
      link: 'https://twitter.com/HomerJSimpson',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/offical_homersimpson/',
      createdAt: '2021-12-02',
      updatedAt: '2021-12-02',
    },
    ],
  },
  ],
}];
